services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pm20261
      MYSQL_DATABASE: pm20261_db
      MYSQL_USER: pm20261_user
      MYSQL_PASSWORD: pm20261_user_pass
    ports:
      - "4406:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pm20261-network

volumes:
  mysql_data:

networks:
  pm20261-network:
    driver: bridge